# Generated by Django 4.2.16 on 2024-09-27 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='favorite_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subcriptions',
        ),
    ]
